#!/usr/bin/env Rscript

# Test script to verify metafor forest plot generation

library(metafor)

# Create sample data
df <- data.frame(
  study = paste("Study", 1:10),
  effect_size = c(0.2, 0.3, 0.4, 0.1, 0.5, 0.35, 0.25, 0.45, 0.15, 0.38),
  variance = c(0.04, 0.05, 0.03, 0.06, 0.04, 0.05, 0.04, 0.03, 0.07, 0.04)
)

# Run meta-analysis
ma_result <- rma(yi = effect_size, vi = variance, data = df, method = "REML")

# Print model info to confirm it's a metafor object
cat("Meta-analysis model class:", class(ma_result), "\n")
cat("Overall effect:", round(ma_result$beta, 3), "\n")
cat("I-squared:", round(ma_result$I2, 1), "%\n\n")

# Generate forest plot
png("test-data/metafor_forest_plot_demo.png", width = 1200, height = 800, res = 120)

# This is the exact same forest() call from our mcp_tools.R
forest(ma_result, 
       slab = df$study,
       xlim = c(-1, 1),
       xlab = "Effect Size",
       mlab = paste0("RE Model (I² = ", round(ma_result$I2, 1), "%)"),
       header = TRUE,
       shade = TRUE,
       col = "darkblue",
       border = "darkblue")

title(main = "Forest Plot Generated by metafor::forest()")

dev.off()

cat("Forest plot saved to: test-data/metafor_forest_plot_demo.png\n")
cat("This demonstrates that the MVP IS using metafor's forest() function.\n")