name: Auto Rerun Failed CI (one retry)

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types: [completed]

jobs:
  rerun-on-failure:
    # Only rerun if the tracked workflow failed and we haven't retried yet
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.run_attempt < 2 }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    concurrency:
      group: rerun-${{ github.event.workflow_run.id }}
      cancel-in-progress: false
    steps:
      - name: Rerun failed workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          curl -s -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/rerun

