name: PoC Gradio Build

on:
  workflow_dispatch:
  push:
    branches: [ poc/gradio-chat ]

jobs:
  build-poc:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: ${{ env.DOCKER_HUB_USERNAME != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}
      - name: Build PoC image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: poc/gradio-mcp/Dockerfile.poc
          push: ${{ env.DOCKER_HUB_USERNAME != '' }}
          tags: ${{ env.DOCKER_HUB_USERNAME }}/meta-analysis-mvp-poc:latest
